//Extracts PCode generated by Ghidra after a binary was analysed.
//@author Melvin Klimke
//@category 
//@keybinding
//@menupath
//@toolbar

import ghidra.app.script.GhidraScript;

public class PCodeExtractor extends GhidraScript {

	@Override
	protected void run() throws Exception {
		//TODO: Add script code here
	}
}
